# Generated by Django 5.2.12 on 2026-03-10 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresasCatalogo',
            fields=[
                ('COD', models.IntegerField(primary_key=True, serialize=False)),
                ('pais', models.CharField(max_length=100)),
                ('STATUS', models.IntegerField()),
                ('ORDEN', models.IntegerField()),
                ('donde', models.TextField()),
            ],
            options={
                'db_table': 'empresas_catalogo',
            },
        ),
        migrations.CreateModel(
            name='PagReporte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'pag_reporte',
            },
        ),
        migrations.CreateModel(
            name='IndiceReporte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipos', models.CharField(max_length=100)),
                ('p1', models.IntegerField(blank=True, null=True)),
                ('p2', models.IntegerField(blank=True, null=True)),
                ('p3', models.IntegerField(blank=True, null=True)),
                ('p4', models.IntegerField(blank=True, null=True)),
                ('p5', models.IntegerField(blank=True, null=True)),
                ('p6', models.IntegerField(blank=True, null=True)),
                ('p7', models.IntegerField(blank=True, null=True)),
                ('p8', models.IntegerField(blank=True, null=True)),
                ('p9', models.IntegerField(blank=True, null=True)),
                ('p10', models.IntegerField(blank=True, null=True)),
                ('p11', models.IntegerField(blank=True, null=True)),
                ('p12', models.IntegerField(blank=True, null=True)),
                ('p13', models.IntegerField(blank=True, null=True)),
                ('p14', models.IntegerField(blank=True, null=True)),
                ('p16', models.IntegerField(blank=True, null=True)),
                ('p17', models.IntegerField(blank=True, null=True)),
                ('p18', models.IntegerField(blank=True, null=True)),
                ('p19', models.IntegerField(blank=True, null=True)),
                ('p20', models.IntegerField(blank=True, null=True)),
                ('p21', models.IntegerField(blank=True, null=True)),
                ('id_empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.DO_NOTHING, to='app.empresascatalogo')),
            ],
            options={
                'db_table': 'INDICE_REPORTE',
            },
        ),
        migrations.CreateModel(
            name='HiDeIndicadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('inci_menor_o_8', models.FloatField(blank=True, null=True)),
                ('inci_mayor_a_8', models.FloatField(blank=True, null=True)),
                ('productividad', models.FloatField(blank=True, null=True)),
                ('sitios_reincidentes', models.FloatField(blank=True, null=True)),
                ('indice_de_reincidencia', models.FloatField(blank=True, null=True)),
                ('mttr_promedio', models.FloatField(blank=True, null=True)),
                ('disponibilidad', models.FloatField(blank=True, null=True)),
                ('proactividad', models.FloatField(blank=True, null=True)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.DO_NOTHING, to='app.empresascatalogo')),
            ],
            options={
                'db_table': 'hi_de_indicadores',
                'unique_together': {('id_cliente', 'mes', 'ano')},
            },
        ),
        migrations.CreateModel(
            name='ParqueCnoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('sitios_activos', models.IntegerField(blank=True, null=True)),
                ('tt_EnlacesDatos', models.IntegerField(blank=True, null=True)),
                ('internet', models.IntegerField(blank=True, null=True)),
                ('AE', models.IntegerField(blank=True, null=True)),
                ('tt_tt', models.IntegerField(blank=True, null=True)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.DO_NOTHING, to='app.empresascatalogo')),
            ],
            options={
                'db_table': 'parque_cnoc',
                'unique_together': {('id_cliente', 'mes', 'ano')},
            },
        ),
    ]
