# Generated by Django 5.2.12 on 2026-03-10 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagreporte',
            old_name='titulo',
            new_name='cliente',
        ),
        migrations.RemoveField(
            model_name='indicereporte',
            name='id_empresa',
        ),
        migrations.RemoveField(
            model_name='indicereporte',
            name='p1',
        ),
        migrations.RemoveField(
            model_name='indicereporte',
            name='p10',
        ),
        migrations.RemoveField(
            model_name='indicereporte',
            name='p11',
        ),
        migrations.RemoveField(
            model_name='indicereporte',
            name='p12',
        ),
        migrations.RemoveField(
            model_name='indicereporte',
            name='p13',
        ),
        migrations.RemoveField(
            model_name='indicereporte',
            name='p14',
        ),
        migrations.RemoveField(
            model_name='indicereporte',
            name='p16',
        ),
        migrations.RemoveField(
            model_name='indicereporte',
            name='p17',
        ),
        migrations.RemoveField(
            model_name='indicereporte',
            name='p18',
        ),
        migrations.RemoveField(
            model_name='indicereporte',
            name='p19',
        ),
        migrations.RemoveField(
            model_name='indicereporte',
            name='p2',
        ),
        migrations.RemoveField(
            model_name='indicereporte',
            name='p20',
        ),
        migrations.RemoveField(
            model_name='indicereporte',
            name='p21',
        ),
        migrations.RemoveField(
            model_name='indicereporte',
            name='p3',
        ),
        migrations.RemoveField(
            model_name='indicereporte',
            name='p4',
        ),
        migrations.RemoveField(
            model_name='indicereporte',
            name='p5',
        ),
        migrations.RemoveField(
            model_name='indicereporte',
            name='p6',
        ),
        migrations.RemoveField(
            model_name='indicereporte',
            name='p7',
        ),
        migrations.RemoveField(
            model_name='indicereporte',
            name='p8',
        ),
        migrations.RemoveField(
            model_name='indicereporte',
            name='p9',
        ),
        migrations.RemoveField(
            model_name='indicereporte',
            name='tipos',
        ),
        migrations.RemoveField(
            model_name='pagreporte',
            name='categoria',
        ),
        migrations.AddField(
            model_name='empresascatalogo',
            name='razon_social',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='empresascatalogo',
            name='tipo',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresascatalogo',
            name='tt_sitioa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicereporte',
            name='CNAM',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='indicereporte',
            name='MENSUALES',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='indicereporte',
            name='XT',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='indicereporte',
            name='banrural',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='indicereporte',
            name='titulo',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagreporte',
            name='id_cliente',
            field=models.ForeignKey(db_column='id_cliente', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='app.empresascatalogo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagreporte',
            name='paginas',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
