# Generated by Django 5.2.12 on 2026-03-10 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_titulo_pagreporte_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresascatalogo',
            name='COD',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
