# Generated by Django 5.2.12 on 2026-03-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_empresascatalogo_cod'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresascatalogo',
            name='WhereParque',
            field=models.TextField(blank=True, help_text='PARQUE DE SERVICIO', null=True),
        ),
        migrations.AlterField(
            model_name='empresascatalogo',
            name='donde',
            field=models.TextField(help_text='Condición WHERE para los tickets (where_tk + filtros desde sql_base)'),
        ),
        migrations.AlterField(
            model_name='empresascatalogo',
            name='tt_sitioa',
            field=models.IntegerField(blank=True, help_text='Total de sitios o enlaces monitoreados', null=True),
        ),
    ]
