# Generated by Django 5.2.12 on 2026-03-13 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_empresascatalogo_whereparque_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresascatalogo',
            old_name='WhereParque',
            new_name='parque_where',
        ),
    ]
