# Generated by Django 5.2.12 on 2026-03-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_whereparque_empresascatalogo_parque_where'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresascatalogo',
            name='pais',
            field=models.CharField(choices=[('GT', 'Guatemala'), ('ESV', 'El Salvador'), ('HN', 'Honduras'), ('CR', 'Costa Rica'), ('NI', 'Nicaragua'), ('CENAM', 'Centroamérica')], max_length=10),
        ),
    ]
