# Generated by Django 5.2.12 on 2026-03-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_empresascatalogo_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresascatalogo',
            name='tipo',
            field=models.CharField(choices=[('MENSUALES', 'Mensuales'), ('XT', 'XT'), ('BANRURAL', 'Banrural'), ('CNAM', 'CNAM')], max_length=20),
        ),
    ]
