# Generated by Django 5.2.12 on 2026-03-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_empresascatalogo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hideindicadores',
            name='disponibilidad',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hideindicadores',
            name='inci_mayor_a_8',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hideindicadores',
            name='inci_menor_o_8',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hideindicadores',
            name='indice_de_reincidencia',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hideindicadores',
            name='mttr_promedio',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hideindicadores',
            name='proactividad',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hideindicadores',
            name='productividad',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hideindicadores',
            name='sitios_reincidentes',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
