# Generated by Django 5.2.12 on 2026-03-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_hideindicadores_disponibilidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresascatalogo',
            name='ORDEN',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='empresascatalogo',
            name='STATUS',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='empresascatalogo',
            name='donde',
            field=models.TextField(help_text='Condición WHERE para los tickets (where_tk + filtros desde sql_base)', null=True),
        ),
        migrations.AlterField(
            model_name='empresascatalogo',
            name='pais',
            field=models.CharField(choices=[('GT', 'Guatemala'), ('ESV', 'El Salvador'), ('HN', 'Honduras'), ('CR', 'Costa Rica'), ('NI', 'Nicaragua'), ('CENAM', 'Centroamérica')], max_length=10, null=True),
        ),
    ]
