WITH
VARIABLES AS (
SELECT A.*, 1 COD,
to_char(LAST_DAY(TO_DATE(FECHA_INI) ),'DDMMYYYY') FECHA_FIN,
to_char(LAST_DAY(TO_DATE(FECHA_INI_1) ),'DDMMYYYY') FECHA_FIN_1,
to_char(LAST_DAY(TO_DATE(FECHA_INI_2) ),'DDMMYYYY') FECHA_FIN_2,
to_char(LAST_DAY(TO_DATE(FECHA_INI_3) ),'DDMMYYYY') FECHA_FIN_3,
to_char(LAST_DAY(TO_DATE(FECHA_INI_4) ),'DDMMYYYY') FECHA_FIN_4,
to_char(LAST_DAY(TO_DATE(FECHA_INI_5) ),'DDMMYYYY') FECHA_FIN_5,
TO_CHAR(TO_DATE(FECHA_INI), 'MON-YY', 'NLS_DATE_LANGUAGE=SPANISH') MES,
TO_CHAR(TO_DATE(FECHA_INI_1), 'MON-YY', 'NLS_DATE_LANGUAGE=SPANISH') MES_1,
TO_CHAR(TO_DATE(FECHA_INI_2), 'MON-YY', 'NLS_DATE_LANGUAGE=SPANISH') MES_2,
TO_CHAR(TO_DATE(FECHA_INI_3), 'MON-YY', 'NLS_DATE_LANGUAGE=SPANISH') MES_3,
TO_CHAR(TO_DATE(FECHA_INI_4), 'MON-YY', 'NLS_DATE_LANGUAGE=SPANISH') MES_4,
TO_CHAR(TO_DATE(FECHA_INI_5), 'MON-YY', 'NLS_DATE_LANGUAGE=SPANISH') MES_5

FROM (
SELECT 
to_char(TRUNC(TO_DATE(FECHA_BUSCAR), 'MONTH'),'DDMMYYYY') FECHA_INI,
to_char(ADD_MONTHS(TO_DATE(FECHA_BUSCAR),-1),'DDMMYYYY') FECHA_INI_1,
to_char(ADD_MONTHS(TO_DATE(FECHA_BUSCAR),-2),'DDMMYYYY') FECHA_INI_2,
to_char(ADD_MONTHS(TO_DATE(FECHA_BUSCAR),-3),'DDMMYYYY') FECHA_INI_3,
to_char(ADD_MONTHS(TO_DATE(FECHA_BUSCAR),-4),'DDMMYYYY') FECHA_INI_4,
to_char(ADD_MONTHS(TO_DATE(FECHA_BUSCAR),-5),'DDMMYYYY') FECHA_INI_5
FROM (
SELECT 
'01012026' FECHA_BUSCAR
FROM DUAL) B) A
)
SELECT 
cod,
TO_CHAR(TO_DATE(FECHA_INI), 'MM', 'NLS_DATE_LANGUAGE=SPANISH') MESN,
TO_CHAR(TO_DATE(FECHA_INI_1), 'MM', 'NLS_DATE_LANGUAGE=SPANISH') MESN_1,
TO_CHAR(TO_DATE(FECHA_INI_2), 'MM', 'NLS_DATE_LANGUAGE=SPANISH') MESN_2,
TO_CHAR(TO_DATE(FECHA_INI_3), 'MM', 'NLS_DATE_LANGUAGE=SPANISH') MESN_3,
TO_CHAR(TO_DATE(FECHA_INI_4), 'MM', 'NLS_DATE_LANGUAGE=SPANISH') MESN_4,
TO_CHAR(TO_DATE(FECHA_INI_5), 'MM', 'NLS_DATE_LANGUAGE=SPANISH') MESN_5,
MES,MES_1,MES_2,MES_3,MES_4,MES_5,
FECHA_INI,FECHA_FIN,FECHA_INI_1,FECHA_FIN_1,FECHA_INI_2,FECHA_FIN_2,
FECHA_INI_3,FECHA_FIN_3,FECHA_INI_4,FECHA_FIN_4,
FECHA_INI_5,FECHA_FIN_5,
TO_CHAR(TO_DATE(FECHA_INI_5), 'YYYY', 'NLS_DATE_LANGUAGE=SPANISH') ANO_1,
TO_CHAR(TO_DATE(FECHA_INI), 'YYYY', 'NLS_DATE_LANGUAGE=SPANISH') ANO_2,
TO_CHAR(TO_DATE(FECHA_INI), 'MMYYYY', 'NLS_DATE_LANGUAGE=SPANISH') A,
TO_CHAR(TO_DATE(FECHA_INI_1), 'MMYYYY', 'NLS_DATE_LANGUAGE=SPANISH') B,
TO_CHAR(TO_DATE(FECHA_INI_2), 'MMYYYY', 'NLS_DATE_LANGUAGE=SPANISH') C,
TO_CHAR(TO_DATE(FECHA_INI_3), 'MMYYYY', 'NLS_DATE_LANGUAGE=SPANISH') D,
TO_CHAR(TO_DATE(FECHA_INI_4), 'MMYYYY', 'NLS_DATE_LANGUAGE=SPANISH') E,
TO_CHAR(TO_DATE(FECHA_INI_5), 'MMYYYY', 'NLS_DATE_LANGUAGE=SPANISH') F
FROM VARIABLES;

 -- -------------------------------------------------------- --

WITH
VARIABLES AS (
SELECT 1 COD ,'01012026' F_INI,'31012026' F_FIN FROM DUAL
),
ENLACES AS (

SELECT * FROM P_SERVICE_M WHERE ID_INTERNO=(SELECT COD FROM VARIABLES) 
),
TK AS (
SELECT * FROM TICKETS_2 WHERE ID_INTERNO=(SELECT COD FROM VARIABLES) AND "FECHA DE CIERRE" BETWEEN (SELECT F_INI FROM VARIABLES) AND (SELECT  to_date(F_FIN) +1 FROM VARIABLES)
),
TK_ATRIBUCION_CLIENTE AS (
SELECT * FROM TICKETS_2 WHERE ID_INTERNO=(SELECT COD FROM VARIABLES) AND "ATRIBUIBLE A"='CLIENTE' AND "FECHA DE CIERRE" BETWEEN (SELECT F_INI FROM VARIABLES) AND (SELECT  to_date(F_FIN) +1 FROM VARIABLES)
), TK_PROACTIVOS AS (
    SELECT "TIPO MONITOREO" FROM TK  
), RANGO_SOLUCION AS (
    SELECT "RANGO SOLUCION 2" R,COUNT("RANGO SOLUCION 2") CONTAR FROM TK GROUP BY "RANGO SOLUCION 2"
)

SELECT    NVL(R_MENOR_8,0) R_MENOR_8,
        NVL(R_MAYOR_8,0) R_MAYOR_8,
        CASE
            WHEN R_MENOR_8=0 THEN 0
        ELSE
            NVL(ROUND((R_MENOR_8 / TT_TK)*100,2),0)
        END INDICE_MENOR_8,
        CASE
            WHEN R_MAYOR_8=0 THEN 0
        ELSE
            NVL(ROUND((R_MAYOR_8 / TT_TK)*100,2),0) 
        END INDICE_MAYOR_8,
        CASE
            WHEN PRO=0 THEN 0
        ELSE
            NVL(ROUND((PRO/TT_TK) *100,2),0) END "PROACTIVIDAD",
        CASE
            WHEN TT_TK_CLIENTE=0 THEN 0
        ELSE
            NVL(ROUND(((TT_TK-TT_TK_CLIENTE)/TT_ENLACES)*100,2),0) END "INDICE DE FALLAS",
         NVL(INDI,0) "SITIOS REINCIDENTES",
        CASE
            WHEN INDI=0 THEN 0
        ELSE
            NVL(ROUND( (INDI / TT_ENLACES)*100,2),0) END INDICE_REINCIDENCIA,
            NVL(ROUND( PROMEDIO,2),0) MTR
       FROM (
SELECT  
  NULLIF((SELECT CONTAR FROM RANGO_SOLUCION WHERE R='RANGO DE 0 A 8 HORAS'),0) R_MENOR_8,
    NULLIF((SELECT CONTAR FROM RANGO_SOLUCION WHERE R='RANGO MAS DE 8 HORAS'),0) R_MAYOR_8,
    NULLIF((SELECT COUNT(*) FROM TK),0) TT_TK,
    NULLIF((SELECT COUNT(*) FROM TK_ATRIBUCION_CLIENTE),0) TT_TK_CLIENTE,
    NULLIF((SELECT COUNT(*) FROM ENLACES),0) TT_ENLACES ,
    NULLIF((SELECT COUNT(*) FROM TK_PROACTIVOS WHERE "TIPO MONITOREO"='MONITOREO PROACTIVO'),0) PRO,
    NULLIF((SELECT avg("T TICKET ACTIVO (horas)") FROM TK),0) PROMEDIO,
    NULLIF((SELECT COUNT(ENLACE) ENLACE FROM (SELECT COUNT(ENLACE) ENLACE FROM TK  GROUP BY ENLACE HAVING COUNT(ENLACE)>=2)),0) INDI
    FROM DUAL) A
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    