# Generated by Django 5.2.12 on 2026-04-13 15:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_area', models.CharField(max_length=35)),
                ('estado', models.BooleanField(default=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tb_area',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pais', models.CharField(max_length=20, unique=True)),
                ('ext', models.CharField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tb_pais',
            },
        ),
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=50)),
                ('entity_id', models.IntegerField()),
                ('action', models.CharField(max_length=20)),
                ('payload', models.TextField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=80, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tb_change_log',
                'indexes': [models.Index(fields=['entity'], name='tb_change_l_entity_035bca_idx'), models.Index(fields=['entity_id'], name='tb_change_l_entity__d52bd1_idx'), models.Index(fields=['username'], name='tb_change_l_usernam_5eaaab_idx'), models.Index(fields=['created_at'], name='tb_change_l_created_fac0ea_idx')],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username2', models.CharField(max_length=80, unique=True)),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('ibm', models.IntegerField(unique=True)),
                ('agente', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('baja', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cnoc_app.area')),
            ],
            options={
                'db_table': 'tb_usuario',
            },
        ),
    ]
