# Generated by Django 5.2.12 on 2026-04-13 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cnoc_app', '0002_usuario_area_id_usuario_pass_plain_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='area_id',
        ),
    ]
