# Generated by Django 5.2.12 on 2026-04-13 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cnoc_app', '0005_remove_usuario_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='area_id',
        ),
    ]
