# Generated by Django 5.2.12 on 2026-04-13 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnoc_app', '0006_remove_usuario_area_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cnoc_app.area'),
        ),
    ]
