# Generated by Django 5.2.12 on 2026-04-13 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnoc_app', '0007_usuario_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalacionBitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('date_update', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(max_length=50)),
                ('observaciones', models.TextField()),
                ('tiempo', models.TimeField(blank=True, null=True)),
                ('tipo', models.CharField(default='0', max_length=10)),
                ('falla', models.CharField(default='F00000', max_length=20)),
                ('correlativo', models.CharField(default='0', max_length=50)),
                ('reloj', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'TB_ESCALACION_BITACORA',
            },
        ),
        migrations.CreateModel(
            name='EscalacionFallaAsociada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqID', models.CharField(max_length=50, unique=True)),
                ('tk_masiva', models.CharField(max_length=20)),
                ('tk_id', models.CharField(max_length=20)),
                ('enlace', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('close_time', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('pais', models.CharField(blank=True, max_length=25, null=True)),
                ('pe', models.CharField(blank=True, max_length=15, null=True)),
                ('wan', models.CharField(blank=True, max_length=15, null=True)),
                ('vrf', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('open_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TB_ESCALACION_FALLA_ASOCIADA',
            },
        ),
        migrations.CreateModel(
            name='EscalacionRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('falla_id', models.CharField(blank=True, max_length=20, null=True)),
                ('area_id', models.IntegerField()),
                ('titulo', models.TextField(blank=True, null=True)),
                ('nivel', models.CharField(blank=True, max_length=10, null=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('tiempo', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('hora_apertura', models.TimeField(blank=True, null=True)),
                ('hora_sumada', models.TimeField(blank=True, null=True)),
                ('tiempo_acumulado', models.TimeField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('gestor', models.CharField(max_length=50)),
                ('close_time', models.DateTimeField(blank=True, null=True)),
                ('open_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'TB_ESCALACION_REGISTRO',
            },
        ),
        migrations.CreateModel(
            name='EscalacionTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, unique=True)),
                ('icono', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'TB_ESCALACION_TIPO',
            },
        ),
        migrations.CreateModel(
            name='EscalacionArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_area', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pais', models.ForeignKey(db_column='id_pais', on_delete=django.db.models.deletion.PROTECT, to='cnoc_app.pais')),
            ],
            options={
                'db_table': 'TB_ESCALACION_AREA',
            },
        ),
        migrations.CreateModel(
            name='EscalacionContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('centro', models.CharField(blank=True, max_length=50, null=True)),
                ('comentario', models.CharField(blank=True, max_length=50, null=True)),
                ('supervisor', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pais', models.ForeignKey(blank=True, db_column='id_pais', null=True, on_delete=django.db.models.deletion.PROTECT, to='cnoc_app.pais')),
            ],
            options={
                'db_table': 'TB_ESCALACION_CONTACTO',
            },
        ),
        migrations.CreateModel(
            name='EscalacionReloj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reloj', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
                ('extra', models.BooleanField(default=False)),
                ('area', models.ForeignKey(db_column='area', on_delete=django.db.models.deletion.PROTECT, to='cnoc_app.area')),
            ],
            options={
                'db_table': 'TB_ESCALACION_RELOJ',
            },
        ),
        migrations.CreateModel(
            name='Escalacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=5)),
                ('tiempo', models.CharField(max_length=50)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(db_column='id_area', on_delete=django.db.models.deletion.PROTECT, to='cnoc_app.escalacionarea')),
                ('tipo_contacto', models.ForeignKey(db_column='tipo_contacto', on_delete=django.db.models.deletion.PROTECT, to='cnoc_app.escalacioncontacto')),
                ('tipo_escalacion', models.ForeignKey(blank=True, db_column='id_tipo_escalacion', null=True, on_delete=django.db.models.deletion.PROTECT, to='cnoc_app.escalaciontipo')),
            ],
            options={
                'db_table': 'TB_ESCALACION',
            },
        ),
        migrations.AddIndex(
            model_name='escalacionarea',
            index=models.Index(fields=['pais'], name='idx_esc_area_pais'),
        ),
        migrations.AddIndex(
            model_name='escalacionarea',
            index=models.Index(fields=['activo'], name='idx_esc_area_activo'),
        ),
    ]
