# Generated by Django 5.2.12 on 2026-04-13 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnoc_app', '0008_escalacionbitacora_escalacionfallaasociada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matriz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=5)),
                ('filas', models.IntegerField()),
                ('columnas', models.IntegerField()),
                ('estado', models.BooleanField()),
                ('creado', models.IntegerField()),
            ],
            options={
                'db_table': 'TB_ASIENTO_MATRIZ',
            },
        ),
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.IntegerField()),
                ('columna', models.IntegerField()),
                ('color', models.CharField(blank=True, max_length=32, null=True)),
                ('estado', models.CharField(choices=[('disponible', 'disponible'), ('bloqueado', 'bloqueado'), ('mantenimiento', 'mantenimiento')], default='disponible', max_length=15)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(db_column='area_id', on_delete=django.db.models.deletion.PROTECT, to='cnoc_app.area')),
                ('matriz', models.ForeignKey(blank=True, db_column='matiz', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cnoc_app.matriz')),
            ],
            options={
                'db_table': 'TB_ASIENTO',
            },
        ),
        migrations.CreateModel(
            name='AsignacionAsiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isoweek', models.SmallIntegerField()),
                ('isoyear', models.SmallIntegerField()),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('estado', models.CharField(choices=[('tomado', 'tomado'), ('libre', 'libre')], default='tomado', max_length=10)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(db_column='area_id', on_delete=django.db.models.deletion.PROTECT, to='cnoc_app.area')),
                ('asiento', models.ForeignKey(db_column='asiento_id', on_delete=django.db.models.deletion.PROTECT, to='cnoc_app.asiento')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, to='cnoc_app.usuario', to_field='ibm')),
            ],
            options={
                'db_table': 'TB_ASIENTO_ASIGNACION',
            },
        ),
        migrations.CreateModel(
            name='HorarioUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.SmallIntegerField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(choices=[('activo', 'activo'), ('inactivo', 'inactivo')], default='activo', max_length=10)),
                ('tipo', models.CharField(default='Rotativo', max_length=15)),
                ('vigencia_desde', models.DateField()),
                ('vigencia_hasta', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, to='cnoc_app.usuario', to_field='ibm')),
            ],
            options={
                'db_table': 'TB_ASIENTO_HORARIO_USUARIO',
            },
        ),
        migrations.AddConstraint(
            model_name='asiento',
            constraint=models.UniqueConstraint(fields=('area', 'matriz', 'fila', 'columna'), name='uq_asiento_posicion'),
        ),
    ]
