# Generated by Django 5.2.12 on 2026-04-13 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnoc_app', '0009_matriz_asiento_asignacionasiento_horariousuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hallazgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField()),
                ('f_creacion', models.DateTimeField(auto_now_add=True)),
                ('eliminado', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'TB_RETRO_HALLAZGO',
            },
        ),
        migrations.CreateModel(
            name='Retroalimentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('falla', models.CharField(max_length=100, unique=True)),
                ('assignment', models.CharField(blank=True, max_length=80, null=True)),
                ('update_action', models.TextField(blank=True, null=True)),
                ('variable3', models.CharField(blank=True, max_length=80, null=True)),
                ('hr_act', models.DateTimeField(blank=True, null=True)),
                ('hr_update', models.DateTimeField(blank=True, null=True)),
                ('seguimiento', models.DateTimeField(blank=True, null=True)),
                ('date_creado', models.DateTimeField(blank=True, null=True)),
                ('estado', models.IntegerField()),
                ('hallazgo', models.ForeignKey(db_column='id_hallazgo', on_delete=django.db.models.deletion.PROTECT, to='cnoc_app.hallazgo')),
                ('usuario', models.ForeignKey(db_column='USER_IBM', on_delete=django.db.models.deletion.PROTECT, to='cnoc_app.usuario', to_field='ibm')),
            ],
            options={
                'db_table': 'TB_RETRO_RETROALIMENTACION',
            },
        ),
        migrations.CreateModel(
            name='RetroLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('falla_id', models.CharField(max_length=100)),
                ('fecha_seguimiento', models.DateField()),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True)),
                ('extra', models.CharField(blank=True, max_length=20, null=True)),
                ('hallazgo', models.ForeignKey(db_column='id_hallazgo', null=True, on_delete=django.db.models.deletion.PROTECT, to='cnoc_app.hallazgo')),
                ('usuario', models.ForeignKey(db_column='USER_IBM', on_delete=django.db.models.deletion.PROTECT, to='cnoc_app.usuario', to_field='ibm')),
            ],
            options={
                'db_table': 'TB_RETRO_LOG',
            },
        ),
        migrations.CreateModel(
            name='Tomados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=50)),
                ('ventana', models.CharField(max_length=50)),
                ('hora', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('extra', models.CharField(blank=True, max_length=20, null=True)),
                ('usuario', models.ForeignKey(db_column='ibm_usu', on_delete=django.db.models.deletion.PROTECT, to='cnoc_app.usuario', to_field='ibm')),
            ],
            options={
                'db_table': 'TB_RETRO_TOMADO',
            },
        ),
    ]
