# Generated by Django 5.2.12 on 2026-04-13 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnoc_app', '0010_hallazgo_retroalimentacion_retrologs_tomados'),
    ]

    operations = [
        migrations.AddField(
            model_name='hallazgo',
            name='usuario',
            field=models.ForeignKey(db_column='USER_IBM', default=1, on_delete=django.db.models.deletion.PROTECT, to='cnoc_app.usuario', to_field='ibm'),
            preserve_default=False,
        ),
    ]
